name: Test the action

on:
  workflow_dispatch: {}
  push:
    branches:
    - main

jobs:
  build-margo:
    runs-on: ubuntu-22.04
    name: Build the latest version of margo
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Use mochi-test-build-action@main to build mochi-margo"
        uses: mochi-hpc/mochi-test-build-action@main
        with:
          package-name: mochi-margo
          build-cache-token: ${{ secrets.GITHUB_TOKEN }}
          push-only-dependencies: false

      - name: "Use mochi-test-build-action@main to build mochi-margo@main"
        uses: mochi-hpc/mochi-test-build-action@main
        with:
          package-name: mochi-margo
          package-version: '@main'
          build-cache-token: ${{ secrets.GITHUB_TOKEN }}

